# --- MADDPG specific parameters ---

runner: "episode"

buffer_size: 3000
target_update_interval_or_tau: 100

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# MADDPG components
mac: "maddpg_mac"
learner: "maddpg_learner"
critic_type: "maddpg_critic"

# Training params
batch_size: 32
lr: 0.00005
reg: 0.001
grad_norm_clip: 5

# Architecture
use_rnn: True
hidden_dim: 128
agent_output_type: "pi_logits"

# Normalization
standardise_returns: False
standardise_rewards: True

# Misc
name: "maddpg"