# Level-Based Foraging - Phase 1 (state vector observations)
env: "gymma"
env_args:
  time_limit: 500
  key: "lbforaging:Foraging-8x8-2p-2f-v3"
  pretrained_wrapper: null
n_agents: 2
n_actions: 6
episode_limit: 500
label: "lbf"
common_reward: True
reward_scalarisation: "sum"