# Overcooked-AI - Heterogeneous team
env: "gymma"
env_args:
  time_limit: 400
  key: "overcooked_ai:CoordinationRing-v0"
  pretrained_wrapper: null
  pixel_obs: true
  obs_size: 84
n_agents: 2
n_actions: 6
obs_shape: [3, 84, 84]
episode_limit: 400
label: "overcooked"
common_reward: True
reward_scalarisation: "sum"